name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2023-03-01
version: '9.5.4'
project: 'drupal'
datestamp: 1677680891
